import { PinataSDK } from "pinata-web3";

 export const pinata = new PinataSDK({
  pinataJwt: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIxYTAwNzk1OC05MTk4LTRkZGItYjRiMC1jMDhmNTg4YTFkNDUiLCJlbWFpbCI6InNoYWtlYmthbXJhbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiMzBmYjNkOTJmYjVmMTM4NWFhMWQiLCJzY29wZWRLZXlTZWNyZXQiOiI5Y2VkMmZkMGMzNTVjM2Q4MGQyNzMxNGY5MDRkODE3ZGRkNTc3YmVhOWFjYTgzMmY4Yjg1NmQwMzM3MWMwMWM4IiwiZXhwIjoxNzcwNDg2MzE2fQ.z8KotvIJKsh5Nwt6xVkES1G3U6wqAp3-mnal8FyOElg`,
  pinataGateway: `indigo-acceptable-parakeet-211.mypinata.cloud`,
});
